apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config-script
data:
  keycloak-config.sh: |
    #!/bin/sh
    set -e

    keycloak_api_call() {
      COMMAND=$1
      export RESPONSE=$(eval $COMMAND)
      ERROR=$(echo "$RESPONSE" | jq -r 'try if type == "array" then .[0].error else .error end')
      if [ -n "$ERROR" ] && [ "null" != "$ERROR" ]; then
        echo "Error from Keycloak: $RESPONSE"
        exit 1
      fi
    }
    echo "Waiting for Keycloak to be ready..."
    until curl --output /dev/null --silent --head --fail $KEYCLOAK_SERVER_URL; do
        echo '.'
        sleep 5
    done

    ACCESS_TOKEN=$(curl -s -X POST "$KEYCLOAK_SERVER_URL/realms/master/protocol/openid-connect/token" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=admin-cli" -d "grant_type=password" -d "username=tmpadmin" -d "password=$KEYCLOAK_ADMIN_PASSWORD" | jq -r '.access_token')
    if [ "$ACCESS_TOKEN" = "null" ]; then
      NEW_ACCESS_TOKEN=$(curl -s -X POST "$KEYCLOAK_SERVER_URL/realms/master/protocol/openid-connect/token" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=admin-cli" -d "grant_type=password" -d "username=admin" -d "password=$KEYCLOAK_ADMIN_PASSWORD" | jq -r '.access_token')
      if [ "$NEW_ACCESS_TOKEN" = "null" ]; then
        echo "Couldn't login using either the \"admin\" or \"tmpadmin\" accounts."
        exit 1;
      fi
      ACCESS_TOKEN=$NEW_ACCESS_TOKEN
    fi

    keycloak_api_call "curl -s \"$KEYCLOAK_SERVER_URL/admin/realms/master/users?username=admin&exact=true\" -H \"Authorization: Bearer $ACCESS_TOKEN\""
    if [ "[]" = "$RESPONSE" ]; then
      echo "Creating new admin user..."
      keycloak_api_call "curl -s -X POST \"$KEYCLOAK_SERVER_URL/admin/realms/master/users\" \
        -H \"Authorization: Bearer $ACCESS_TOKEN\" \
        -H \"Content-Type: application/json\" \
        -d \"{
          \\\"username\\\": \\\"admin\\\",
          \\\"enabled\\\": true,
          \\\"emailVerified\\\": true,
          \\\"firstName\\\": \\\"Keycloak\\\",
          \\\"lastName\\\": \\\"Admin\\\",
          \\\"email\\\": \\\"admin@all-hands.dev\\\",
          \\\"credentials\\\": [{
          \\\"type\\\": \\\"password\\\",
          \\\"value\\\": \\\"$KEYCLOAK_ADMIN_PASSWORD\\\",
          \\\"temporary\\\": false
          }]
        }\""

      keycloak_api_call "curl -s \"$KEYCLOAK_SERVER_URL/admin/realms/master/users?username=admin&exact=true\" -H \"Authorization: Bearer $ACCESS_TOKEN\""
      ADMIN_ID=$(echo "$RESPONSE" | jq -r '.[0].id')

      keycloak_api_call "curl -s \"$KEYCLOAK_SERVER_URL/admin/realms/master/roles/admin\" -H \"Authorization: Bearer $ACCESS_TOKEN\" -H \"Content-Type: application/json\""
      ADMIN_ROLE=$(echo "$RESPONSE" | sed 's/"/\\"/g')

      keycloak_api_call "curl -s \"$KEYCLOAK_SERVER_URL/admin/realms/master/roles/create-realm\" -H \"Authorization: Bearer $ACCESS_TOKEN\" -H \"Content-Type: application/json\""
      CREATE_ROLE=$(echo "$RESPONSE" | sed 's/"/\\"/g')

      keycloak_api_call "curl -s -X POST \"$KEYCLOAK_SERVER_URL/admin/realms/master/users/$ADMIN_ID/role-mappings/realm\" \
        -H \"Authorization: Bearer $ACCESS_TOKEN\" \
        -H \"Content-Type: application/json\" \
        -d \"[$ADMIN_ROLE]\""
      keycloak_api_call "curl -s -X POST \"$KEYCLOAK_SERVER_URL/admin/realms/master/users/$ADMIN_ID/role-mappings/realm\" \
        -H \"Authorization: Bearer $ACCESS_TOKEN\" \
        -H \"Content-Type: application/json\" \
        -d \"[$CREATE_ROLE]\""

      keycloak_api_call "curl -s -X POST \"$KEYCLOAK_SERVER_URL/realms/master/protocol/openid-connect/token\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"client_id=admin-cli\" -d \"grant_type=password\" -d \"username=admin\" -d \"password=$KEYCLOAK_ADMIN_PASSWORD\""
      ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

      keycloak_api_call "curl -s \"$KEYCLOAK_SERVER_URL/admin/realms/master/users?username=tmpadmin&exact=true\" -H \"Authorization: Bearer $ACCESS_TOKEN\""
      TMPADMIN_ID=$(echo "$RESPONSE" | jq -r '.[0].id')
      keycloak_api_call "curl -s -X DELETE \"$KEYCLOAK_SERVER_URL/admin/realms/master/users/$TMPADMIN_ID\" -H \"Authorization: Bearer $ACCESS_TOKEN\""

      echo "Created new user \"admin\". The password can be found in the \"keycloak-admin\" secret."
    else
      echo "User already exists: $RESPONSE"
    fi

    ERROR_MESSAGE=$(curl -s "$KEYCLOAK_SERVER_URL/admin/realms/$KEYCLOAK_REALM_NAME" -H "Authorization: Bearer $ACCESS_TOKEN" | jq -r '.error')
    echo "Error message: $ERROR_MESSAGE"
    export GITHUB_BASE_URL=""
    if [ "$GITHUB_PROXY" = "1" ]; then
      export GITHUB_BASE_URL="https://{{ .Values.ingress.host }}/github-proxy/test-auth-feat"
    fi
    if [ "$ERROR_MESSAGE" = "Realm not found." ]; then
      echo "Creating allhands realm..."
      envsubst '$WEB_HOST,$AUTH_WEB_HOST,$KEYCLOAK_REALM_NAME,$KEYCLOAK_PROVIDER_NAME,$KEYCLOAK_CLIENT_ID,$KEYCLOAK_CLIENT_SECRET,$GITHUB_APP_CLIENT_ID,$GITHUB_APP_CLIENT_SECRET,$GITLAB_APP_CLIENT_ID,$GITLAB_APP_CLIENT_SECRET,$BITBUCKET_APP_CLIENT_ID,$BITBUCKET_APP_CLIENT_SECRET,$AZURE_DEVOPS_APP_CLIENT_ID,$AZURE_DEVOPS_APP_CLIENT_SECRET,$GITHUB_BASE_URL,$KEYCLOAK_SMTP_PASSWORD'< /app/allhands-realm-github-provider.json.tmpl > /app/allhands-realm-github-provider.json
      keycloak_api_call "curl -s -X POST \"$KEYCLOAK_SERVER_URL/admin/realms\" -H \"Authorization: Bearer $ACCESS_TOKEN\" -H \"Content-Type: application/json\" --data \"@/app/allhands-realm-github-provider.json\""
      echo "Created allhands realm."
    fi